server:
  port: 9080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db?autoReconnect=true&useSSL=false
    username: user
    password: user123
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: none
